# Generated by Django 4.1.7 on 2023-04-13 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=40)),
                ('adress', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'country code is not required')])),
                ('pinCode', models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(default='', max_length=30)),
                ('price', models.FloatField(default='', max_length=10)),
                ('maxQty', models.FloatField(default='', max_length=10)),
                ('dTime', models.DateField(default='')),
                ('PImage', models.ImageField(default='', upload_to='shop/uploads')),
                ('phone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phone+', to='Home.register')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quant', models.FloatField(default='', max_length=10)),
                ('sPrc', models.FloatField(default='', max_length=10)),
                ('aTime', models.DateField(default='')),
                ('dTime', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dTime+', to='Home.upload')),
                ('pImage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pImage+', to='Home.upload')),
                ('pName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pName+', to='Home.upload')),
                ('phone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Home.register')),
            ],
        ),
    ]
