# Generated by Django 4.1.6 on 2023-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cimg',
            field=models.ImageField(default='', upload_to='shop/uploads'),
        ),
        migrations.AddField(
            model_name='register',
            name='cpassword',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='fimg',
            field=models.ImageField(default='', upload_to='shop/uploads'),
        ),
        migrations.AddField(
            model_name='register',
            name='pimg',
            field=models.ImageField(default='', upload_to='shop/uploads'),
        ),
    ]
