# Generated by Django 4.1.7 on 2023-04-11 06:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.FloatField(default='', max_length=10)),
                ('sPrc', models.FloatField(default='', max_length=10)),
                ('aTime', models.DateTimeField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='Name',
        ),
        migrations.AlterField(
            model_name='register',
            name='adress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'country code is not required')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='pinCode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='PImage',
            field=models.ImageField(default='', upload_to='shop/uploads'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='dTime',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='maxQty',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='pName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Home.register'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='price',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='pImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pImage+', to='Home.upload'),
        ),
        migrations.AddField(
            model_name='order',
            name='pName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pName+', to='Home.upload'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Home.register'),
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
