# Generated by Django 4.1.7 on 2023-04-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_order_remove_register_name_alter_register_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dTime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dTime+', to='Home.upload'),
        ),
        migrations.AlterField(
            model_name='order',
            name='aTime',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='dTime',
            field=models.DateField(default=''),
        ),
    ]
