# Generated by Django 4.1.7 on 2023-04-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_register_cimg_register_cpassword_register_fimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cpassword',
        ),
    ]
