# Generated by Django 4.1.6 on 2023-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_register_cimg_register_cpassword_register_fimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='cpassword',
            new_name='type',
        ),
    ]
