# Generated by Django 4.1.6 on 2023-04-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_cpassword_register_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='type',
            new_name='typ',
        ),
    ]
