# Generated by Django 4.1.7 on 2023-04-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_order_dtime_alter_order_atime_alter_upload_dtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phone+', to='Home.register'),
        ),
    ]
